function P_getResources() //预加载图片及音频资源
{
    return [
        {src:"./assets/pic/food/zhurou.png", id:"0", class:"food"},
        {src:"./assets/pic/food/doufu.png", id:"1", class:"food"},
        {src:"./assets/pic/food/suan.png", id:"2", class:"food"},
        {src:"./assets/pic/food/niurou.png", id:"3", class:"food"},
        {src:"./assets/pic/food/tudou.png", id:"4", class:"food"},
        {src:"./assets/pic/food/xianggu.png", id:"5", class:"food"},
        {src:"./assets/pic/food/nangua.png", id:"6", class:"food"},
        {src:"./assets/pic/food/jiang.png", id:"7", class:"food"},
        {src:"./assets/pic/food/baijiu.png", id:"8", class:"food"},
        {src:"./assets/pic/food/yangrou.png", id:"9", class:"food"},
        {src:"./assets/pic/food/cha.png", id:"10", class:"food"},
        {src:"./assets/pic/food/cu.png", id:"11", class:"food"},
        {src:"./assets/pic/food/zhusun.png", id:"12", class:"food"},
        {src:"./assets/pic/food/bocai.png", id:"13", class:"food"},
        {src:"./assets/pic/food/lizi.png", id:"14", class:"food"},
        {src:"./assets/pic/food/qingjiao.png", id:"15", class:"food"},
        {src:"./assets/pic/food/juzi.png", id:"16", class:"food"},
        {src:"./assets/pic/food/youcai.png", id:"17", class:"food"},
        {src:"./assets/pic/food/jirou.png", id:"18", class:"food"},
        {src:"./assets/pic/food/huanggua.png", id:"19", class:"food"},
        {src:"./assets/pic/food/qincai.png", id:"20", class:"food"},
        {src:"./assets/pic/food/jiucai.png", id:"21", class:"food"},
        {src:"./assets/pic/food/fengmi.png", id:"22", class:"food"},
        {src:"./assets/pic/food/lvdouya.png", id:"23", class:"food"},
        {src:"./assets/pic/food/xiangjiao.png", id:"24", class:"food"},
        {src:"./assets/pic/food/fanqie.png", id:"25", class:"food"},
        {src:"./assets/pic/food/mantou.png", id:"26", class:"food"},
        {src:"./assets/pic/food/qiezi.png", id:"27", class:"food"},
        {src:"./assets/pic/food/pangxie.png", id:"28", class:"food"},
        {src:"./assets/pic/food/huluobo.png", id:"29", class:"food"},
        {src:"./assets/pic/food/donggua.png", id:"30", class:"food"},
        {src:"./assets/pic/food/jiayu.png", id:"31", class:"food"},
        {src:"./assets/pic/food/xia.png", id:"32", class:"food"},
        {src:"./assets/pic/food/luo.png", id:"33", class:"food"},
        {src:"./assets/pic/food/heimuer.png", id:"34", class:"food"},
        {src:"./assets/pic/food/dami.png", id:"35", class:"food"},
        {src:"./assets/pic/food/yu.png", id:"36", class:"food"},
        {src:"./assets/pic/food/cong.png", id:"37", class:"food"},
        {src:"./assets/pic/food/pingguo.png", id:"38", class:"food"},
        {src:"./assets/pic/food/tao.png", id:"39", class:"food"},
        {src:"./assets/pic/food/li.png", id:"40", class:"food"},
        {src:"./assets/pic/food/niunai.png", id:"41", class:"food"},
        {src:"./assets/pic/food/mianbao.png", id:"42", class:"food"},
        {src:"./assets/pic/button/back.png", id:"back", class:"button"},
        {src:"./assets/pic/button/back2.png", id:"back2", class:"button"},
        {src:"./assets/pic/button/help.png", id:"help", class:"button"},
        {src:"./assets/pic/button/help2.png", id:"help2", class:"button"},
        {src:"./assets/pic/button/menu.png", id:"menu", class:"button"},
        {src:"./assets/pic/button/menu2.png", id:"menu2", class:"button"},
        {src:"./assets/pic/button/next.png", id:"next", class:"button"},
        {src:"./assets/pic/button/next2.png", id:"next2", class:"button"},
        {src:"./assets/pic/button/off.png", id:"off", class:"button"},
        {src:"./assets/pic/button/off2.png", id:"off2", class:"button"},
        {src:"./assets/pic/button/on.png", id:"on", class:"button"},
        {src:"./assets/pic/button/on2.png", id:"on2", class:"button"},
        {src:"./assets/pic/button/pause.png", id:"pause", class:"button"},
        {src:"./assets/pic/button/pause2.png", id:"pause2", class:"button"},
        {src:"./assets/pic/button/play.png", id:"play", class:"button"},
        {src:"./assets/pic/button/play2.png", id:"play2", class:"button"},
        {src:"./assets/pic/button/rank.png", id:"rank", class:"button"},
        {src:"./assets/pic/button/rank2.png", id:"rank2", class:"button"},
        {src:"./assets/pic/button/recipes.png", id:"recipes", class:"button"},
        {src:"./assets/pic/button/recipes2.png", id:"recipes2", class:"button"},
        {src:"./assets/pic/button/replay.png", id:"replay", class:"button"},
        {src:"./assets/pic/button/replay2.png", id:"replay2", class:"button"},
        {src:"./assets/pic/button/resume.png", id:"resume", class:"button"},
        {src:"./assets/pic/button/resume2.png", id:"resume2", class:"button"},
        {src:"./assets/pic/button/setting.png", id:"setting", class:"button"},
        {src:"./assets/pic/button/setting2.png", id:"setting2", class:"button"},
        {src:"./assets/pic/background/diet.png", id:"diet", class:"background"},
        {src:"./assets/pic/background/pause.png", id:"bgdpause", class:"background"},
        {src:"./assets/pic/background/ending.png", id:"bgdending", class:"background"},
        {src:"./assets/pic/background/game.png", id:"bgdgame", class:"background"},
        {src:"./assets/pic/background/menu.png", id:"bgdmenu", class:"background"},
        {src:"./assets/pic/poopoo/cry.png", id:"cry", class:"poopoo"},
        {src:"./assets/pic/poopoo/smile.png", id:"smile", class:"poopoo"},
        {src:"./assets/pic/monster/monster1.png", id:"monster1", class:"monster"},
        {src:"./assets/pic/monster/monster2.png", id:"monster2", class:"monster"},
        {src:"./assets/pic/choosetrackbox70x70.png", id:"choosetrackbox", class:"frame"},
        {src:"./assets/pic/enzymechoicebox70x420.png", id:"enzymechoicebox", class:"frame"},
        {src:"./assets/pic/hpBar.png", id:"hpBar", class:"frame"},
        {src:"./assets/pic/hpBase.png", id:"hpBase", class:"frame"},
        {src:"./assets/pic/enzyme/0.png", id:"enzyme0", class:"enzyme"},
        {src:"./assets/pic/enzyme/1.png", id:"enzyme1", class:"enzyme"},
        {src:"./assets/pic/enzyme/2.png", id:"enzyme2", class:"enzyme"},
        {src:"./assets/pic/enzyme/3.png", id:"enzyme3", class:"enzyme"},
        {src:"./assets/pic/enzyme/4.png", id:"enzyme4", class:"enzyme"},
        {src:"./assets/pic/enzyme/5.png", id:"enzyme5", class:"enzyme"},
        {src:"./assets/audio/bgm1.mp3", id:"bgdAudio1", class:"audio"},
        {src:"./assets/audio/bgm2.mp3", id:"bgdAudio2", class:"audio"},
        {src:"./assets/audio/btnClick.mp3", id:"btnClick", class:"audio"},
        {src:"./assets/audio/changeScene.mp3", id:"changeScene", class:"audio"},
        {src:"./assets/audio/foodArrive.wav", id:"foodArrive", class:"audio"},
        {src:"./assets/audio/putEnzyme.wav", id:"putEnzyme", class:"audio"}
    ];
}

function P_getFoodImageList(){//从所有预加载资源中提取出食物图片
    var list = P_getResources();
    var foodImageList = new Array();
    for(var i = 0;i < list.length;i++)
    {
        if(list[i].class == "food")
        {
            foodImageList.push(list[i]);
        }
    }
    return foodImageList;
}

function P_getFoodInfo(){//获取食物信息
    return [
    {"id":0,"name":"猪肉","value":9,"state":6,"info":"富含蛋白质，铁质，防贫血，对热病、燥咳、便秘有疗效。"},
    {"id":1,"name":"豆腐","value":8,"state":6,"info":"蛋白质含量高，保护肝脏，增加免疫力，解毒。"},
    {"id":2,"name":"蒜","value":17,"state":6,"info":"促进食欲，预防心脏病，抗肿瘤，抗衰老，防止铅中毒。"},
    {"id":3,"name":"牛肉","value":6,"state":6,"info":"含锌、铁、蛋白质、B族维生素，益于肌肉生长，补脾胃，益气血，强筋骨。"},
    {"id":4,"name":"土豆","value":6,"state":6,"info":"富含维生素、膳食纤维，补血强肾、预防癌症和心脏病，帮助通便，增强免疫力。"},
    {"id":5,"name":"香菇","value":7,"state":2,"info":"高蛋白质、低脂肪，多氨基酸，多维生素，促进食欲、抗癌、提高人体免疫力。"},
    {"id":6,"name":"南瓜","value":4,"state":2,"info":"富含维生素矿物质膳食纤维，增强抵抗力，防心血管疾病，延缓衰老，对挑你奥冰、高血压也有辅助疗效。"},
    {"id":7,"name":"姜","value":21,"state":6,"info":"散寒止呕，促进血液循环，增进食欲，防止胆结石，抗衰老。"},
    {"id":8,"name":"白酒","value":11,"state":4,"info":"发酵蒸馏而来，含有人体所需的氨基酸矿物质。"},
    {"id":9,"name":"羊肉","value":9,"state":6,"info":"富含维生素及矿物质，促进血液循环，皮肤红润，开胃健力。"},
    {"id":10,"name":"茶","value":8,"state":6,"info":"抗氧化的作用，防止心血管疾病，预防蛀牙。"},
    {"id":11,"name":"醋","value":13,"state":7,"info":"降低血压和胆固醇，山君消毒，增进食欲，促进吸收。"},
    {"id":12,"name":"竹笋","value":3,"state":6,"info":"富含膳食纤维、微量元素及多种氨基酸，低脂肪，性热化痰、利水消肿、润肠通便。"},
    {"id":13,"name":"菠菜","value":12,"state":2,"info":"含大量胡萝卜素、铁、维生素B6，防贫血，润起色。"},
    {"id":14,"name":"栗子","value":3,"state":6,"info":"养胃健脾，预防和治疗高血压冠心病等心血管疾病。"},
    {"id":15,"name":"青椒","value":6,"state":6,"info":"有抗氧化的维生素和微量元素，增强体力，环节辅料，防治坏血病。"},
    {"id":16,"name":"橘子","value":6,"state":4,"info":"止咳润肺，有助于缓解动脉粥样硬化。"},
    {"id":17,"name":"油菜","value":5,"state":6,"info":"胡萝卜素、维生素C、膳食纤维、矿物质，对医治吐血、病肿、痔疮等有显著疗效。"},
    {"id":18,"name":"鸡肉","value":9,"state":6,"info":"氨基酸种类多，容易被吸收利用，可强壮身体。"},
    {"id":19,"name":"黄瓜","value":4,"state":4,"info":"富含水分矿物质，清热、利尿、解毒、除湿、润肠。"},
    {"id":20,"name":"芹菜","value":3,"state":6,"info":"富含胡萝卜素、维生素C、膳食纤维、矿物质，降血压。"},
    {"id":21,"name":"韭菜","value":3,"state":6,"info":"蛋白质、脂肪、碳水化合物、钙、胡萝卜素、维生素，有补肾益阳、消炎杀菌的功效。"},
    {"id":22,"name":"蜂蜜","value":17,"state":7,"info":"保健补品，防止胆结石，抗衰老，解除疲劳，增强抵抗力，解酒。"},
    {"id":23,"name":"绿豆芽","value":6,"state":6,"info":"富含膳食纤维，预防消化道癌，利尿除湿、解酒、清热解毒。"},
    {"id":24,"name":"香蕉","value":5,"state":4,"info":"富含钾离子，预防神经疲劳，防治便秘。"},
    {"id":25,"name":"番茄","value":8,"state":6,"info":"有特殊的番茄红素，预防前列腺癌，治疗牙龈出血，增强抵抗力，促进伤口愈合，祛斑美容。"},
    {"id":26,"name":"馒头","value":8,"state":5,"info":"富含维生素B1，维生素E，蛋白质，能加速伤口愈合，有效消除黑眼圈现象。"},
    {"id":27,"name":"茄子","value":7,"state":2,"info":"维生素P含量高，防止血管硬化和破裂，防治高血压、冠心病、动脉硬化、对胃和十二指肠溃疡也有疗效。"},
    {"id":28,"name":"螃蟹","value":10,"state":2,"info":"有抗酸化的胡萝卜素，预防动脉硬化。癌症及防止机体老化，强化心肺功能，预防贫血，还有醒酒的功效。"},
    {"id":29,"name":"胡萝卜","value":3,"state":7,"info":"蛋白质、脂肪、钾、钙、磷、丰富胡萝卜素，保护视力、减缓身体衰老，防癌，提高免疫力。"},
    {"id":30,"name":"冬瓜","value":8,"state":2,"info":"富含维生素矿物质，治疗水肿，祛痰，慢性气管炎，利尿消肿。"},
    {"id":31,"name":"甲鱼","value":10,"state":2,"info":"营养丰富，滋补良品，预防和抑制肝癌、胃癌，净血，降低胆固醇，对高血压，冠心病有益。"},
    {"id":32,"name":"虾","value":8,"state":6,"info":"富含的脂肪易于人体吸收，微量元素含量高，化痰止咳，促进伤口愈合，补肾壮阳。"},
    {"id":33,"name":"螺","value":5,"state":4,"info":"健胃，促进食欲，醒酒解热，治反胃、痢疾等，有明目功效"},
    {"id":34,"name":"黑木耳","value":6,"state":6,"info":"含铁高、蛋白质、维生素，对于冠心病，动脉硬化，心脑血管疾病有益。"},
    {"id":35,"name":"大米","value":8,"state":7,"info":"聪耳明目，健脾养胃，富含的维生素E有消融胆固醇的神奇功效，降血压，还可预防动脉硬化。"},
    {"id":36,"name":"鱼","value":5,"state":2,"info":"富含蛋白质，易于被人体吸收，益气健脾，开胃调气。"},
    {"id":37,"name":"葱","value":16,"state":6,"info":"散寒发汗，祛痰健胃，增进食欲，防治癌症的发生。"},
    {"id":38,"name":"苹果","value":22,"state":6,"info":"富含果胶和苹果酸，消除便秘，稳定血糖，清理肠道，预防大肠癌，预防糖尿病。"},
    {"id":39,"name":"桃","value":13,"state":6,"info":"富含铁，活血祛斑，润燥滑肠，止咳平喘。"},
    {"id":40,"name":"梨","value":11,"state":6,"info":"止咳化痰，清热降火，提高记忆力、注意力。"},
    {"id":41,"name":"牛奶","value":10,"state":1,"info":"营养价值很高，矿物质种类丰富是人体钙的最佳来源，而且钙磷比例非常适当，利于钙的吸收。"},
    {"id":42,"name":"面包","value":8,"state":1,"info":"富含维生素B1，维生素E，蛋白质，能加速伤口愈合，有效消除黑眼圈现象。"},
    ];
}
function P_getDietInfo(){//获取搭配信息
    return [
    {"begin":0,"end":1,"value":-8,"reason":"影响吸收，引起腹胀"},
    {"begin":0,"end":2,"value":5,"reason":"促进血液循环，增强体质"},
    {"begin":3,"end":4,"value":2,"reason":"保护胃黏膜"},
    {"begin":3,"end":5,"value":3,"reason":"易于消化和吸收"},
    {"begin":3,"end":6,"value":1,"reason":"健胃"},
    {"begin":3,"end":7,"value":2,"reason":"驱寒，治腹痛"},
    {"begin":3,"end":8,"value":-6,"reason":"上火，牙齿发炎"},
    {"begin":9,"end":7,"value":-4,"reason":"腰背酸冷"},
    {"begin":9,"end":6,"value":-4,"reason":"胸闷腹胀"},
    {"begin":9,"end":10,"value":-2,"reason":"便秘"},
    {"begin":9,"end":11,"value":-8,"reason":"性味相反，不宜同吃"},
    {"begin":9,"end":1,"value":-8,"reason":"功能相反，不宜同吃"},
    {"begin":9,"end":12,"value":-2,"reason":"中毒"},
    {"begin":13,"end":15,"value":2,"reason":"保护眼睛"},
    {"begin":13,"end":1,"value":-7,"reason":"不利于钙的吸收"},
    {"begin":17,"end":5,"value":1,"reason":"防便秘"},
    {"begin":17,"end":1,"value":2,"reason":"清肺止咳"},
    {"begin":17,"end":18,"value":2,"reason":"强化肝脏"},
    {"begin":17,"end":19,"value":-8,"reason":"降低维生素C吸收"},
    {"begin":20,"end":3,"value":2,"reason":"营养瘦身"},
    {"begin":21,"end":22,"value":-2,"reason":"腹泻"},
    {"begin":21,"end":13,"value":-2,"reason":"腹泻"},
    {"begin":21,"end":3,"value":-9,"reason":"发热动火"},
    {"begin":21,"end":8,"value":-6,"reason":"上火，胃肠不适"},
    {"begin":12,"end":1,"value":-2,"reason":"结石"},
    {"begin":4,"end":11,"value":3,"reason":"分解有毒物质"},
    {"begin":4,"end":24,"value":-4,"reason":"面部生斑"},
    {"begin":4,"end":25,"value":-4,"reason":"消化不良"},
    {"begin":25,"end":20,"value":3,"reason":"降压，健胃消食"},
    {"begin":25,"end":19,"value":-6,"reason":"破坏维生素C"},
    {"begin":25,"end":6,"value":-6,"reason":"破坏维生素C"},
    {"begin":15,"end":26,"value":4,"reason":"有利于维生素C吸收"},
    {"begin":15,"end":19,"value":-6,"reason":"破坏维生素C"},
    {"begin":27,"end":0,"value":-8,"reason":"降低胆固醇的吸收"},
    {"begin":27,"end":18,"value":-8,"reason":""},
    {"begin":27,"end":28,"value":-4,"reason":"损伤肠胃"},
    {"begin":29,"end":22,"value":1,"reason":"排毒"},
    {"begin":29,"end":15,"value":-6,"reason":"破坏维生素C"},
    {"begin":29,"end":11,"value":1,"reason":"破坏胡萝卜素"},
    {"begin":29,"end":25,"value":-9,"reason":"不利于维生素的吸收"},
    {"begin":19,"end":22,"value":2,"reason":"润肠通便"},
    {"begin":19,"end":25,"value":-6,"reason":"破坏维生素C"},
    {"begin":19,"end":13,"value":-6,"reason":"破坏维生素C"},
    {"begin":19,"end":32,"value":-2,"reason":"痢疾"},
    {"begin":30,"end":18,"value":1,"reason":"清热"},
    {"begin":30,"end":31,"value":2,"reason":"明目，减肥"},
    {"begin":6,"end":0,"value":3,"reason":"保健，预防糖尿病"},
    {"begin":6,"end":9,"value":-2,"reason":"黄疸"},
    {"begin":5,"end":1,"value":1,"reason":"相互促进吸收"},
    {"begin":31,"end":18,"value":-2,"reason":"不能一起吃"},
    {"begin":33,"end":34,"value":-5,"reason":"不利于消化"},
    {"begin":33,"end":3,"value":-5,"reason":"不利于消化"},
    {"begin":33,"end":26,"value":-4,"reason":"腹泻呕吐"},
    {"begin":32,"end":6,"value":-2,"reason":"伤身"},
    {"begin":35,"end":29,"value":3,"reason":"改善胃肠功能"},
    {"begin":1,"end":36,"value":1,"reason":"补钙"},
    {"begin":1,"end":29,"value":2,"reason":"有助于消化"},
    {"begin":1,"end":37,"value":-6,"reason":"影响钙质吸收"},
    {"begin":1,"end":22,"value":-2,"reason":"腹泻"},
    {"begin":38,"end":10,"value":1,"reason":"抗癌"},
    {"begin":24,"end":4,"value":2,"reason":"防止结肠癌"},
    {"begin":39,"end":41,"value":2,"reason":"滋养皮肤"},
    {"begin":39,"end":31,"value":-2,"reason":"心痛"},
    {"begin":40,"end":28,"value":-2,"reason":"腹泻"},
    {"begin":40,"end":0,"value":-3,"reason":"伤肾脏"},
    {"begin":16,"end":41,"value":-7,"reason":"影响蛋白质吸收"},
    {"begin":37,"end":0,"value":5,"reason":"增强体质，预防老年痴呆"},
    {"begin":37,"end":1,"value":-2,"reason":"结石"},
    {"begin":37,"end":22,"value":-4,"reason":"腹胀腹泻"},
    {"begin":7,"end":11,"value":4,"reason":"减缓恶性，呕吐症状"},
    {"begin":7,"end":28,"value":2,"reason":"杀菌解毒"},
    {"begin":7,"end":8,"value":-3,"reason":"伤脾胃"},
    {"begin":2,"end":22,"value":-2,"reason":"便秘"},
    {"begin":2,"end":9,"value":-4,"reason":"体内燥热"},
    {"begin":11,"end":8,"value":-2,"reason":"胃炎"},
    {"begin":22,"end":31,"value":4,"reason":"有助于心血管疾病"},
    {"begin":22,"end":21,"value":-2,"reason":"腹泻"},
    {"begin":10,"end":8,"value":-5,"reason":"影响肾功能"},
    {"begin":24,"end":41,"value":5,"reason":"提高对B12的吸收"},
    {"begin":8,"end":41,"value":2,"reason":"保护肝脏"},
    {"begin":8,"end":28,"value":-2,"reason":"腹泻"}
    ];
}

function P_getEnzymeInfo(){//获取酶信息
    return [
    {"id":0,"name":"A","cost":10,"atk":9,"af":40,"range":2.5,"info":"0"},
    {"id":1,"name":"B","cost":25,"atk":18,"af":60,"range":3,"info":"1"},
    {"id":2,"name":"C","cost":20,"atk":2,"af":8,"range":2.5,"info":"2"},
    {"id":3,"name":"D","cost":50,"atk":69,"af":320,"range":3,"info":"3"},
    {"id":4,"name":"E","cost":20,"atk":16,"af":100,"range":2,"info":"4"},
    {"id":5,"name":"F","cost":30,"atk":34,"af":80,"range":6.5,"info":"5"}
    ];
}
